<section class="about-wrapper">
    <h3 class="about-title">
        <?= __('Welcome to our Ciepłe Pieczywo Bakery!') ?>
    </h3>
    <div class="about-content">
        <img class="bakery-image" src="<?= $block->getViewFileUrl('images/bakery.png') ?>" alt="bakery" />
        <span class="about-description">
            <?= __('Our bakery is a place where the freshness and aroma of baked bread bloom every day. With a long tradition coming from the heart of baking, we would like to share with you the extraordinary experience of taste and smell that only a real bakery can provide. Our experienced bakers work with passion to create the highest quality bread for you. Our breads, rolls and baguettes are distinguished by their crispy crust, soft interior and distinctive taste. Each order is a unique challenge for us, and fresh ingredients and traditional recipes are our secret.') ?>
        </span>
    </div>
    <div class="about-content">
        <img class="bakery-hero-image" src="<?= $block->getViewFileUrl('images/bakery-hero.png') ?>" alt="bakery-hero" />
        <span class="about-description">
            <?= __('At Ciepłe Pieczywo Bakery, we do not just offer bread - we offer a unique culinary and baking experience. For us, each piece of bread is a work of art, and each customer is like a family member. Come to our bakery and feel the aromatic scents that will take you on a journey to the world of taste and baking traditions. Try our unique breads and enjoy the true joy of eating. Something special is being baked here - we are waiting for you with a warm smile and even warmer bread!') ?>
        </span>
    </div>
</section>