<section class="form-container">
    <div>
        <h2 class="title">
            <?= __('Share your opinion') ?>
        </h2>
    </div>
    <form class="form-content" action="#" method="post" id="custom-form-mockup" data-mage-init='{"validation": {}}'>
        <div class="field">
            <label for="name" class="label">
                <span>
                    <?= __('Name') ?>
                </span>
                <span class="required">*</span>
            </label>
            <div class="control">
                <input name="name" id="name" title="<?= __('Name') ?>" class="input-text" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field">
            <label for="email" class="label">
                <span>
                    <?= __('Email') ?>
                </span>
                <span class="required">*</span>
            </label>
            <div class="control">
                <input name="email" id="email" title="<?= __('Email') ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>

        <div class="field">
            <label for="description" class="label">
                <span>
                    <?= __('Description') ?>
                </span>
                <span class="required">*</span>
            </label>
            <div class="control">
                <textarea name="description" id="description" title="<?= __('Description') ?>" class="input-text" data-validate="{required:true, 'minlength':50}"></textarea>
            </div>
        </div>
        <div class="action-section">
            <button type="submit" title="<?= __('Submit') ?>" class="action submit primary">
                <span>
                    <?= __('Submit') ?>
                </span>
            </button>
        <div>
    </form>
</section>
